nguage: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.4
script: bundle exec rspec
before_install:
  # fixes Travis CI error: NoMethodError: undefined method `spec' for nil:NilClass
  - gem install bundler
